#!/bin/sh
# Use arguments to set git settings
if [ ! -z "$1" ]; then 
    git config user.name $1
fi 

if [ ! -z "$2" ]; then 
    git config user.email $2
fi 

# Create package names and replace file defaults
package_name=$(basename `git rev-parse --show-toplevel`)
package_author=$(git config user.name)
package_email=$(git config user.email)
package_url=$(git remote get-url origin)

echo "# $package_name" > README.md
sed -i "" s/REPLACE_NAME/$package_name/g setup.py
sed -i "" s/REPLACE_AUTHOR/$package_author/g setup.py
sed -i "" s/REPLACE_EMAIL/$package_email/g setup.py 
sed -i "" s,REPLACE_URL,$package_url,g setup.py
django-admin startapp $(echo $package_name | sed -e s,-,_,g)

echo "Project initialized..."
echo "Tip: recursive-include package/templates * for MANIFEST.in"

rm initialize
git add *
git rm initialize
git commit -m "Overwrite template settings, initialize project"
git push origin master 